# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: mysql2
  database: food_development
  pool: 5
  timeout: 5000
  username: root
  password: password
  host: 127.0.0.1

test:
  adapter: mysql2
  database: food_test
  pool: 5
  timeout: 5000
  username: root
  password: password
  host: 127.0.0.1

production:
  adapter: mysql2
  database: food_production
  pool: 5
  timeout: 5000
  username: root
  password: password
  host: 127.0.0.1
